version: '3.3'

volumes:
    foodgram_pg_data_production:
    static:
    media:

services:
  db:
    image: postgres:13
    env_file: /home/yc-user/foodgram/.env
    volumes:
      - foodgram_pg_data_production:/var/lib/postgresql/data

  backend:
    image: dianakim9319/foodgram_backend
    restart: always
    ports:
      - "8090:8000"
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
    env_file: /home/yc-user/foodgram/.env

  frontend:
    image: dianakim9319/foodgram_frontend
    env_file: /home/yc-user/foodgram/.env
    command: cp -r /app/build/. /frontend_static/
    volumes:
        - static:/frontend_static

  nginx:
    image: dianakim9319/foodgram_gateway
    env_file: /home/yc-user/foodgram/.env
    restart: always
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles/
      - media:/media/
    depends_on:
      - backend
