version: '3.3'

volumes:
    foodgram_pg_data_production:
    static:
    media:

services:
  db:
    image: postgres:13
    restart: always
    env_file: /home/yc-user/foodgram/.env
    volumes:
      - foodgram_pg_data_production:/var/lib/postgresql/data

  backend:
    image: dianakim9319/foodgram_backend
    restart: always
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db
    env_file: /home/yc-user/foodgram/.env

  frontend:
    image: dianakim9319/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
        - static:/static
    env_file: /home/yc-user/foodgram/.env

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/sites-enabled/default
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/usr/share/nginx/html/
      - media:/var/html/media/
    depends_on:
      - db
      - backend
      - frontend
