version: '3.3'

volumes:
    foodgram_pg_data_production:
    static:
    media:

services:
  frontend:
    image: dianakim9319/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13
    env_file: /home/yc-user/foodgram/.env
    volumes:
      - foodgram_pg_data_production:/var/lib/postgresql/data

  backend:
    image: dianakim9319/foodgram_backend
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/sites-enabled/default
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles
      - media:/media/
    depends_on:
      - backend
